name: Build azure-cdn-endpoint

on:
  push:
    paths:
      - .github/workflows/azure-cdn-endpoint.yml
      - azure-cdn-endpoint/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: azure-cdn-endpoint
    steps:
      - uses: actions/checkout@v2
      - run: az bicep build --file main.bicep