name: Build azure-static-web-apps

on:
  push:
    paths:
      - .github/workflows/azure-static-web-apps.yml
      - azure-static-web-apps/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: azure-static-web-apps
    steps:
      - uses: actions/checkout@v2
      - run: az bicep build --file main.bicep
